[package]
name = "zopfli"
version = "0.7.2"
description = "A Rust implementation of the Zopfli compression algorithm."
license = "Apache-2.0"
keywords = ["compression"]
homepage = "https://github.com/zopfli-rs/zopfli"
repository = "https://github.com/zopfli-rs/zopfli"
readme = "README.md"
categories = ["compression"]
exclude = ["test/*"]
edition = "2021"
rust-version = "1.60"

[dependencies]
crc32fast = { version = "1.3.2", default-features = false, optional = true }
simd-adler32 = { version = "0.3.5", default-features = false, optional = true }
typed-arena = { version = "2.0.2", default-features = false }
log = "0.4.17"

[features]
default = ["gzip", "zlib"]
gzip = ["dep:crc32fast"]
zlib = ["dep:simd-adler32"]

nightly = ["crc32fast?/nightly", "simd-adler32?/nightly"]

[[bin]]
name = "zopfli"
required-features = ["gzip", "zlib"]

[profile.release]
debug = true

# docs.rs uses a nightly toolchain, so it can leverage unstable rustdoc features.
# Reference: https://docs.rs/about/builds
[package.metadata.docs.rs]
cargo-args = ["--features", "nightly"]
