[package]
name = "zopfli"
version = "0.6.0"
description = "A Rust implementation of the Zopfli compression algorithm."
license = "Apache-2.0"
keywords = ["compression"]
homepage = "https://github.com/zopfli-rs/zopfli"
repository = "https://github.com/zopfli-rs/zopfli"
readme = "README.md"
categories = ["compression"]
exclude = ["test/*"]
edition = "2021"
rust-version = "1.56"

[dependencies]
crc = "2"
adler32 = "1"
byteorder = "1"
typed-arena = "2"
iter-read = "0.3"
log = "0.4"

[profile.release]
debug = true
