[package]
name = "zopfli"
version = "0.7.0"
description = "A Rust implementation of the Zopfli compression algorithm."
license = "Apache-2.0"
keywords = ["compression"]
homepage = "https://github.com/zopfli-rs/zopfli"
repository = "https://github.com/zopfli-rs/zopfli"
readme = "README.md"
categories = ["compression"]
exclude = ["test/*"]
edition = "2021"
rust-version = "1.56"

[dependencies]
crc = "3.0.0"
adler32 = "1.2.0"
byteorder = "1.4.3"
typed-arena = "2.0.1"
iter-read = "0.3.1"
log = "0.4.17"

[profile.release]
debug = true
